add handlerService incomplete and fix errors
gabiMaglia/PF_HENRY pull request #34
Opened 2023-12-04 22:58 UTC by valen07dido

corregi algunos errores en las relaciones, y añadi una parte de los handlers, me falta aun pero tengo que hacer unas cosas.
revisalo y avisame cualquier consulta.

2023-12-04 23:10 UTC, gabiMaglia requested changes
valen metiste el controlador dentro del handler..la creacion de las entradas de dato no son responsabilidad del handler, el handler solo toma peticion y devuelve respuestas

2023-12-05 00:08 UTC, valen07dido commented
Me guie en los que estaban ya estaban armados de ustedes, porque yo lo arme mal. al principio lo arme en el controller y me di cuenta que las consulta se hacia en el handler. entonces me perdi. como lo manejamos?

2023-12-05 22:55 UTC, valen07dido commented
gabi ahi añadi todo, me faltaria ver como llegan los datos luego de actualizar pero la base funciona.

2023-12-06 00:06 UTC, gabiMaglia approved these changes
perfect

2023-12-06 00:06 UTC, closed without merging